config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root 'posts#index'
  # 管理者用
  namespace :admins do
    resources :posts, except: %i(new show)
    resources :users, only: %i(index destroy)
  end
  # user用
  scope :users do
    resources :informations, only: %i(index)
    resources :logins, only: %i(index)
    resources :users , only: %i(show)
    resources :posts , only: %i(index show) do
      collection do
        get  'search'
        post 'search'
      end
      resources :comments, only: %i(create destroy)
      resources :likes, only: %i(create destroy)
      resources :bookmarks, only: %i(create destroy)
    end
  end
  # vue.js用
  namespace :api do
    resources :posts, only: %i(show)
  end
  # タグ用
  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/models/post.rb
class Post < ApplicationRecord

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :admin
  acts_as_taggable
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :bookmarks, dependent: :destroy

  validates :name, presence: true
  validates :payment, presence: true
  validates :station, presence: true
  validates :rest_day, presence: true
  validates :place, presence: true
  validates :open_time, presence: true
  validates :store_url, presence: true

  def bookmark_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end
  
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController
  before_action :admin_user
  before_action :all_tags , only: %i(index edit)
  before_action :post_find , only: %i(edit update destroy)

  def index
    @post = Post.new 
    @post.images.new

    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all.includes(:images)
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to admins_posts_path
    else
      render :index
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to admins_posts_path
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to admins_posts_path
    else
      render :index
    end
  end

  private

  def post_params
    params.require(:post).permit(:name,
                                 :payment,
                                 :station,
                                 :rest_day,
                                 :place,
                                 :open_time, 
                                 :store_url,
                                 tag_list: [], 
                                 images_attributes: [:image, :_destroy, :id]).merge(admin_id: current_admin.id)
  end

end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
    render 'show', formats: 'json', handlers: 'jbuilder'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :all_tags       , only: %i(index)
  before_action :post_find      , only: %i(show)
  before_action :all_store      , only: %i(index show)

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag_list])
    else
      @posts = Post.all.includes(:images).order('created_at DESC').limit(4)
    end
    @post = Post.new
  end

  def show
    @comment = @post.comments.new
    @like = Like.new
    @bookmark = Bookmark.new
    @bookmarks = Bookmark.where(post_id: @post.id).all
    @image = Image.where(post_id: @post.id).all
    @comments = @post.comments.includes(:user)
  end

  def search
    if post_params[:tag_list]
      @search_posts = Post.where("name LIKE ?", "%#{post_params[:name]}%")
      @search_posts = @search_posts.tagged_with(post_params[:tag_list], match_all: false)
    else
      redirect_to ({action: 'index'}), alert: 'タグを入力してください'
    end
  end

  private

  def post_params
    params.require(:post).permit(tag_list:[])
  end
  
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_average.html.erb
<script type="application/javascript">
  $(document).on('turbolinks:load', function() {
    $('#star-rate-<%= post.id%>').raty({
      size: 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      half: true,
      readOnly: true,
      score: "<%= post.comments.average(:rate).to_f.round(1) %>",
    });
  });
</script>

app/views/posts/_show_raty.html.erb
<div class="comments">
  <h4>＜コメント一覧＞</h4>
  <% if comments %>
    <% comments.each do |comment| %>
      <p class="comment_border">
        <strong><%= comment.user.nickname %>：</strong>
        <%= comment.title %>
        <div id="star-rate-<%= comment.id %>"></div>
        <%= comment.text %>
        <% if admin_signed_in? || user_signed_in? && current_user.id == comment.user_id || current_admin %>
          <%=link_to "削除", post_comment_path(comment.post.id, comment.id), method: :delete %>
        <% end %>
      </p>
      <hr>
      <script type="application/javascript">
        $(document).on('turbolinks:load', function() {
          $('#star-rate-<%= comment.id %>').raty({
            size: 36,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: '<%= comment.rate %>',
          });
        });
      </script>
    <% end %>
  <% end %>
</div>

app/views/posts/_tag_section.html.erb
<div class="tag__section--search">
  <div class="tag-title">検索</div>
    <%= form_for(post, url: {controller: 'posts', action: 'search' }, html: {method: 'GET'}) do |f| %>
      <br>
      <div class="form_check-line form_check-sub form-check-inline check_box">
        <% tags.each do |tag| %>
          <div class="check-group">
            <%= f.check_box :tag_list , { multiple: true , class: 'interested input' }, "#{tag.name}", nil %>
            <%= f.label " #{tag.name}(#{tag.taggings_count})", class: 'interested label tag-btn'%>
          </div>
        <% end %>
      </div>
      <%= f.submit "検索", class: 'submit btn btn-outline-primary' %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.haml
.image__section
  = image_tag 'patrick-tomasso-GXXYkSwndP4-unsplash' , class: "image__section--size"

.tag__section
  = render 'tag_section', post: @post , tags: @tags

.js-postsIndex1
  .all_store
    .all_store-recommend
      .space
        %p.left.store_adjust #新着
        - @new_store.each do |post|
          .separate_store
            .separate_store-list
              %span.v_click{'v-on:click': "setPostInfo(#{post.id})"}
                .image_list
                  = image_tag post.images.first.image.url , class: "image_list-size"
                .store_block
                  = post.name
                .store_block
                  = icon("fas", "far fa-heart")
                  = post.liked_users.count
                  = icon("fas", "comment")
                  = post.comments.count
                = link_to "詳細を見る", post_path(post), class: "show_detail" , data: {"turbolinks": false}
                - if admin_signed_in? && current_admin.administrator?
                  = link_to("削除", admins_post_path(post), method: :delete)
                  = link_to("編集", edit_admins_post_path(post))

        %p.right
        .row{'v-show': 'postInfoBool', 'v-cloak': ""}
          .col.s12.m12
            .card.blue-grey.darken-1
              .card-content.white-text
                .show_info {{ postInfo.name }}
                .show_info
                  %i.fas.fa-map-marker-alt.inline
                  {{ postInfo.place }}
                .show_info 
                  %i.fas.fa-subway.inline
                  {{ postInfo.station }}
                .show_info
                  %i.far.fa-clock.inline
                  .show_info-content {{ postInfo.open_time }}
.js-postsIndex2
  .all_store
    .all_store-recommend
      .space
        %p.left.store_adjust #おすすめ
        - @recommend.each do |post|
          .separate_store
            .separate_store-list
              %span.v_click{'v-on:click': "setPostInfo(#{post.id})"}
                .image_list
                  = image_tag post.images.first.image.url , class: "image_list-size"
                .store_block
                  = post.name
                .store_block
                  = icon("fas", "far fa-heart")
                  = post.liked_users.count
                  = icon("fas", "comment")
                  = post.comments.count
                = link_to "詳細を見る", post_path(post), class: "show_detail" , data: {"turbolinks": false}
                - if admin_signed_in? && current_admin.administrator?
                  = link_to("削除", admins_post_path(post), method: :delete)
                  = link_to("編集", edit_admins_post_path(post))
        %p.right
        .row{'v-show': 'postInfoBool', 'v-cloak': ""}
          .col.s12.m12
            .card.blue-grey.darken-1
              .card-content.white-text
                .show_info {{ postInfo.name }}
                .show_info
                  %i.fas.fa-map-marker-alt.inline
                  {{ postInfo.place }}
                .show_info 
                  %i.fas.fa-subway.inline
                  {{ postInfo.station }}
                .show_info
                  %i.far.fa-clock.inline
                  .show_info-content {{ postInfo.open_time }}

.js-postsIndex3
  .all_store
    .all_store-recommend
      .space
        %p.left.store_adjust #和食
        - @washoku.each do |post|
          .separate_store
            .separate_store-list
              %span.v_click{'v-on:click': "setPostInfo(#{post.id})"}
                .image_list
                  = image_tag post.images.first.image.url , class: "image_list-size"
                .store_block
                  = post.name
                .store_block
                  = icon("fas", "far fa-heart")
                  = post.liked_users.count
                  = icon("fas", "comment")
                  = post.comments.count
                = link_to "詳細を見る", post_path(post), class: "show_detail" , data: {"turbolinks": false}
                - if admin_signed_in? && current_admin.administrator?
                  = link_to("削除", admins_post_path(post), method: :delete)
                  = link_to("編集", edit_admins_post_path(post))
        %p.right
        .row{'v-show': 'postInfoBool', 'v-cloak': ""}
          .col.s12.m12
            .card.blue-grey.darken-1
              .card-content.white-text
                .show_info {{ postInfo.name }}
                .show_info
                  %i.fas.fa-map-marker-alt.inline
                  {{ postInfo.place }}
                .show_info 
                  %i.fas.fa-subway.inline
                  {{ postInfo.station }}
                .show_info
                  %i.far.fa-clock.inline
                  .show_info-content {{ postInfo.open_time }}

.js-postsIndex4
  .all_store
    .all_store-recommend
      .space
        %p.left.store_adjust #洋食
        - @yousyoku.each do |post|
          .separate_store
            .separate_store-list
              %span.v_click{'v-on:click': "setPostInfo(#{post.id})"}
                .image_list
                  = image_tag post.images.first.image.url , class: "image_list-size"
                .store_block
                  = post.name
                .store_block
                  = icon("fas", "far fa-heart")
                  = post.liked_users.count
                  = icon("fas", "comment")
                  = post.comments.count
                = link_to "詳細を見る", post_path(post), class: "show_detail" , data: {"turbolinks": false}
                - if admin_signed_in? && current_admin.administrator?
                  = link_to("削除", admins_post_path(post), method: :delete)
                  = link_to("編集", edit_admins_post_path(post))
        %p.right
        .row{'v-show': 'postInfoBool', 'v-cloak': ""}
          .col.s12.m12
            .card.blue-grey.darken-1
              .card-content.white-text
                .show_info {{ postInfo.name }}
                .show_info
                  %i.fas.fa-map-marker-alt.inline
                  {{ postInfo.place }}
                .show_info 
                  %i.fas.fa-subway.inline
                  {{ postInfo.station }}
                .show_info
                  %i.far.fa-clock.inline
                  .show_info-content {{ postInfo.open_time }}
.adjust_down

= javascript_pack_tag 'posts/index'
= javascript_pack_tag 'posts/index2'
= javascript_pack_tag 'posts/index3'
= javascript_pack_tag 'posts/index4'

app/views/posts/search.html.haml
.search_index
  .search_index-post
    - @search_posts.each do |post|
      .tag_store
        .tag_store-list
          .tag_image
            = image_tag post.images.first.image.url , class: "search_image"
          .search_block
            = link_to "#{post.name}", post_path(post) , data: {"turbolinks": false}
          .search_block
            = icon("fas", "far fa-heart")
            = post.liked_users.count
            = icon("fas", "comment")
            = post.comments.count
.footer-search

app/views/posts/show.html.haml
.post_show_index
  .left_side
    .left_side-space
      .left_side-img
        = image_tag @post.images.first.image.url, class: "show_image"
      .all_photo
        - @image.each do |image|
          %a{ href: "#{image.image.url}" , data: {lightbox: "group"} }
            = image_tag image.image.url, size: "100x100"
      .show_title 
        = @post.name
      %div{id: "star-rate-#{@post.id}" , class: "star_average side_by_side"}
      = render 'posts/average', post: @post
      .like_title.side_by_side
        - if admin_signed_in? || user_signed_in? && current_user.already_liked?(@post) 
          = link_to post_like_path(@post),{ method: :delete, class:"text-deco"} do
            %i.fas.fa-heart.unlike-btn
        - elsif current_user || current_admin
          = link_to post_likes_path(@post),{ method: :post, class:"text-deco"} do
            %i.far.fa-heart.like-btn
        - else
          = link_to logins_path do
            %i.far.fa-heart.unlike-btn
        = @post.likes.count
        - if admin_signed_in? || user_signed_in? && current_user.already_booked?(@post)
          = link_to post_bookmark_path(@post),{ method: :delete , class:"text-deco"} do
            %i.fas.fa-bookmark.unbookmark-btn
        - elsif current_user
          = link_to post_bookmarks_path(@post),{ method: :post , class:"text-deco"} do
            %i.far.fa-bookmark.bookmark-btn
        - else
          = link_to logins_path do
            %i.far.fa-bookmark.unbookmark-btn
        = @bookmarks.count
      .comment_count.side_by_side
      %br
      .post_top_info
        %i.fas.fa-subway
        = @post.station
      .post_top_info
        %i.far.fa-clock
        = @post.open_time
      .post_relative_tag
        = raw(@post.tag_list.map { |t| link_to t, tag_path(t), class: "text-deco" }.join(' '))
      .show_container
        - if current_user 
          = form_for [@post , @comment] do |f| 
            = f.text_field :title, placeholder: "タイトル", class: "form-control form_space"
            .form-group.row#star
              = f.label :rate,'評価', class:'col-md-3 col-form-label'
              = f.hidden_field :rate, id: :review_star
            = f.text_area :text, placeholder: "コメントする", rows: "2", class: "form-control"
            = f.submit "SEND", class: 'btn btn-primary btn_adjust'
      
      = render 'posts/show_raty', comments: @comments
      
      %h2.info 基本情報
      .another_info
        .another_info-title1 住所
        = @post.place
      %hr
      .another_info
        .another_info-title2 定休日
        = @post.rest_day
      %hr
      .another_info
        .another_info-title3 ホームページ
        = @post.store_url
    .footer-adjust

  .right_side
    .first_tag #おすすめ
    - @recommend.each do |p|
      .tag_block
        = image_tag p.images.first.image.url, size: "100x100"
        = link_to "#{p.name}", post_path(p) , data: {"turbolinks": false}
        = icon("fas", "far fa-heart")
        = p.liked_users.count
        = icon("fas", "comment")
        = p.comments.count
        %hr
    .first_tag #新着
    - @new_store.each do |p|
      .tag_block
        = image_tag p.images.first.image.url, size: "100x100"
        = link_to "#{p.name}", post_path(p) , data: {"turbolinks": false}
        = icon("fas", "far fa-heart")
        = p.liked_users.count
        = icon("fas", "comment")
        = p.comments.count
        %hr