config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  root 'posts#index'
  # 管理者用
  namespace :admins do
    resources :posts, except: %i(new show)
    resources :users, only: %i(index destroy)
  end
  # user用
  scope :users do
    resources :informations, only: %i(index)
    resources :logins, only: %i(index)
    resources :users , only: %i(show)
    resources :posts , only: %i(index show) do
      collection do
        get  'search'
        post 'search'
      end
      resources :comments, only: %i(create destroy)
      resources :likes, only: %i(create destroy)
      resources :bookmarks, only: %i(create destroy)
    end
  end
  # vue.js用
  namespace :api do
    resources :posts, only: %i(show)
  end
  # タグ用
  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true,length: { maximum: 6 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :post
  mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :admin
  acts_as_taggable
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :bookmarks, dependent: :destroy

  validates :name, presence: true
  validates :payment, presence: true
  validates :station, presence: true
  validates :rest_day, presence: true
  validates :place, presence: true
  validates :open_time, presence: true
  validates :store_url, presence: true

  def bookmark_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :posts, dependent: :destroy
  has_many :bookmarks, dependent: :destroy 
  has_many :bookmark_posts, through: :bookmarks, source: :post

  validates :nickname, presence: true,length: { maximum: 6 }
  validates :image, uniqueness: true, allow_nil: true

  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end

  def already_booked?(post)
    bookmarks.exists?(post_id: post.id)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_to "/users/posts/#{@like.post.id}", notice: 'いいねしました'
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_to "/users/posts/#{@like.post.id}", alert: 'いいねを取り消しました'
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :all_tags       , only: %i(index)
  before_action :post_find      , only: %i(show)
  before_action :all_store      , only: %i(index show)

  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag_list])
    else
      @posts = Post.all.includes(:images).order('created_at DESC').limit(4)
    end
    @post = Post.new
  end

  def show
    @comment = @post.comments.new
    @like = Like.new
    @bookmark = Bookmark.new
    @bookmarks = Bookmark.where(post_id: @post.id).all
    @image = Image.where(post_id: @post.id).all
    @comments = @post.comments.includes(:user)
  end

  def search
    if post_params[:tag_list]
      @search_posts = Post.where("name LIKE ?", "%#{post_params[:name]}%")
      @search_posts = @search_posts.tagged_with(post_params[:tag_list], match_all: false)
    else
      redirect_to ({action: 'index'}), alert: 'タグを入力してください'
    end
  end

  private

  def post_params
    params.require(:post).permit(tag_list:[])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @bookmarks = Bookmark.where(user_id: current_user.bookmarks)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/admins/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/layouts/_footer.html.haml
.footer
  .footer_nav
    = link_to "favorite storeとは", informations_path,{ class: "footer_list"}
  .footer_copy
    %p ©2020 favorite store All Rights Reserved.

app/views/layouts/_header.html.haml
.header
  .d-flex.flex-column.flex-md-row.align-items-center.p-3.px-md-4.bg-white.border-bottom.shadow-sm
    = link_to "favorite store", root_path, class: "my-0 mr-md-auto font-weight-normal"
    %nav.my-2.my-md-0.mr-md-3
      - if admin_signed_in? && current_admin.administrator?
        = link_to "管理者ログアウト", destroy_admin_session_path,{ method: :delete, class: "p-2 text-dark"}
        = link_to "管理者投稿", admins_posts_path, class: "p-2 text-dark"
      - if user_signed_in?
        = link_to "ログアウト", destroy_user_session_path,{ method: :delete, class: "p-2 text-dark"}
        = link_to "マイページ", "/users/users/#{current_user.id}", class: "p-2 text-dark"
      = link_to "はじめる", logins_path, class: "btn btn-outline-primary"

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag(:div, value, class: "#{key}")

app/views/layouts/_raty.html.erb
<script type="application/javascript">
  $(document).on('turbolinks:load', function() {
    $('#star').raty({
      size     : 36,
      starOff:  '<%= asset_path('star-off.png') %>',
      starOn : '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'comment[rate]',
      half: true,
    });
  });
  history.replaceState(null, document.getElementsByTagName('title')[0].innerHTML, null);
  window.addEventListener('popstate', function(e) {
    window.location.reload();
  });
</script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Favorite store
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href: "https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900"    , rel: "stylesheet"}
    %link{href: "https://cdn.jsdelivr.net/npm/@mdi/font@4.x/css/materialdesignicons.min.css", rel: "stylesheet"}

    %link{href: "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css"   , rel: "stylesheet"}

    %script{type: "application/javascript", src: "https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js"}
  %body
    .all-index
      %header
        = render 'layouts/notifications'
        = render 'layouts/header'
      = yield
      %footer
        = render 'layouts/footer'
    = render 'layouts/raty'